name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov nbclient nbconvert jupyter ipykernel

      - name: Execute notebooks (if any)
        run: |
          if [ -d notebooks ]; then
            shopt -s nullglob
            for nb in notebooks/*.ipynb; do
              (cd "${GITHUB_WORKSPACE}" && jupyter nbconvert --to notebook --execute --inplace \
                --ExecutePreprocessor.timeout=600 "$nb")
            done
          fi

      - name: Run tests + coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest --cov=src --cov-report=term-missing -q
