name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov nbclient nbconvert jupyter
      - name: Execute notebooks
        run: |
          if [ -d notebooks ]; then
            for nb in notebooks/*.ipynb; do
              [ -f "$nb" ] && jupyter nbconvert --to notebook --execute --inplace "$nb"
            done
          fi
      - name: Tests + coverage
        run: pytest --cov=src --cov-report=term-missing -q
